#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Jul 12 13:27:06 2011

import wx
from MainWindow import MainWindow

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_Primary = MainWindow(None, -1, "")
    app.SetTopWindow(frame_Primary)
    frame_Primary.Show()
    #force the user to pick a serial port at the beginning
    frame_Primary.OnChangeSerialPort(None)
    app.MainLoop()
